# Generated by Django 4.2.16 on 2026-08-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_service_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pickup_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
