# Generated by Django 4.2.16 on 2026-08-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('available', 'Available'), ('in_service', 'In Service'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='pending', max_length=20),
        ),
    ]
