# Generated by Django 4.2.16 on 2026-08-05 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
