# Generated by Django 4.2.16 on 2026-08-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('good_condition', 'Good Condition'), ('needs_service', 'Needs Service'), ('under_repair', 'Under Repair'), ('not_in_use', 'Not In Use')], default='good_condition', max_length=20),
        ),
    ]
