# Generated by Django 4.2.16 on 2026-08-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_price_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('pending_check', 'Checking Pending Stage'), ('good_condition', 'Good Condition'), ('needs_service', 'Needs Service'), ('under_repair', 'Under Repair'), ('not_in_use', 'Not In Use')], default='pending_check', max_length=50),
        ),
    ]
